# Generated by Django 2.2.7 on 2020-02-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(help_text='Ayuda => Descripción de la categoría', max_length=100, unique=True),
        ),
    ]
